kind: Secret
apiVersion: v1
metadata:
  name: rabbitmq-backup-daemon-tls-secret
  namespace: rabbitmq
data:
  ca.crt: >-

  tls.crt: >-

  tls.key: >-

type: kubernetes.io/tls

---

kind: Secret
apiVersion: v1
metadata:
  name: rabbitmq-drd-tls-secret
  namespace: rabbitmq
data:
  ca.crt: >-

  tls.crt: >-

  tls.key: >-

type: kubernetes.io/tls

---

kind: Secret
apiVersion: v1
metadata:
  name: rabbitmq-tls-secret
  namespace: rabbitmq
data:
  ca.crt: >-

  tls.crt: >-

  tls.key: >-

type: kubernetes.io/tls

