kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentbit-cluster-reader
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: logging-operator
    meta.helm.sh/release-namespace: logging-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-fluentbit-cluster-role
subjects:
  - kind: ServiceAccount
    name: logging-fluentbit
    namespace: logging-operator
