kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-agent-logging-plugin-view
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: logging-operator
    meta.helm.sh/release-namespace: logging-operator
subjects:
  - kind: ServiceAccount
    name: monitoring-agent-logging-plugin
    namespace: logging-operator
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
