|
  mongodb='
  install: true
  customDataRSParameters:
    - logLevel=0
  storage:
    storageClasses:
      - csi-cinder-sc-delete
  ';
  backup='
  install: true
  storage:
    storageClasses:
      - csi-cinder-sc-delete
  ';
  dbaas='
  install: true
  ';
  robotTests='
  install: true
  ';
  ESCAPE_SEQUENCE=true;
  
