JOB_NAME: ''
JENKINS_URL: ''
TOKEN_NAME: CLOUD_TOKEN
CLOUD_URL: ''
CLOUD_NAMESPACE: jaeger
DESCRIPTOR_NAME: DESCRIPTOR_URL
DEPL\_MODE\: install
KUBECTL_VERSION: 1.18.4
HELM_VERSION: 3.2.1
ADDITIONAL_OPTIONS: []
DEPLOYMENT_PARAMETERS: |
  integrationTests:
    tags: "smokeORha"
    jaegerServiceName: "jaeger"
