JOB_NAME: ''
JENKINS_URL: ''
TOKEN_NAME: CLOUD_TOKEN
CLOUD_URL: ''
CLOUD_NAMESPACE: jaeger
DESCRIPTOR_NAME: DESCRIPTOR_URL
DEPL\_MODE\: clean
KUBECTL_VERSION: 1.18.4
HELM_VERSION: 3.2.1
ADDITIONAL_OPTIONS: []
DEPLOYMENT_PARAMETERS: |
    jaeger:

      storage:
        type: cassandra

    cassandraSchemaJob:
      install: true
      host: cassandra.cassandra-operations.svc
      port: 9042
      keyspace: jaeger
      password: ''
      username: cassandra
      datacenter: dc1
      mode: test
      securityContext:
        runAsUser: 2000
        fsGroup: 2000

    agent:
      install: true
      securityContext:
        runAsUser: 2000
        fsGroup: 2000

    collector:
      install: true
      securityContext:
        runAsUser: 2000
        fsGroup: 2000

    hotrod:
      install: true
      securityContext:
        runAsUser: 2000
        fsGroup: 2000
      agent:
        host: jaeger-app-agent.jaeger.svc
        port: 6831
      ingress:
        install: true
        host: "hotrod-jaeger-test.qa-kubernetes.openshift.sdntest.qubership.org"

    query:
      install: true
      securityContext:
        runAsUser: 2000
        fsGroup: 2000
      ingress:
        install: true
        host: "query-jaeger-test.qa-kubernetes.openshift.sdntest.qubership.org"
