apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: arango-operator-operator-cr-pv
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - watch
      - list