|
  global='
  hweProfile: medium
  ';
  alertManager='
  install: false
  ';
  grafana='
  install: false
  route:
    host: grafana.qa-kubernetes.openshift.sdntest.qubership.org
  resources:
    requests:
      cpu: 300m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 800Mi
  ';
  prometheus='
  install: true
  resources:
    requests:
      cpu: 1000m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 6Gi
  ';
  prometheusRules='
  install: true
  ';
  monitoringOperator='
  install: true
  ';
  kubeStateMetrics='
  install: true
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 150m
      memory: 250Mi
  ';
  nodeExporter='
  install: false
  ';
    victoriametrics='
  vmOperator:
    install: false
  vmAgent:
    install: false
  vmSingle:
    install: false
  vmAlertManager:
    install: false
  vmAlert:
    install: false
  vmAuth:
    install: false
  ';
  ESCAPE_SEQUENCE=true;
  
