# [RabbitMQ] Regression sprint pipeline R2024.4 Sprint 3 (qa_kubernetes)
variables:
  PYTHON_IMAGE: pipe_image_latest
  KUBECTL: /builds/PROD.Platform.HA/Infra.Automation/binary/kubectl
  JOB_NAME_CLEAN: ''
  JOB_NAME_UPDATE: ''
  CLOUD_HOST: ${QA_KUBER_HOST}
  CLOUD_TOKEN: ${QA_KUBER_TOKEN}
  DEPLOY_SCRIPT_APP: /scripts/external_platform_library_builtIn/deploy\_with\_deployer.py
  UPGRADE_CRD_SCRIPT: /scripts/external_platform_library_builtIn/upgrade_crd.py
  APPLY_RESOURCES_SCRIPT: /scripts/external_platform_library_builtIn/prepare_restricted_resources.py
  CLEAN_NS_SCRIPT: /scripts/external_platform_library_builtIn/clean_namespace.py
  PATCH_NS: /scripts/external_platform_library_builtIn/patch_ns_restricted.py
  REPORT_SCRIPT: /scripts/external_platform_library_builtIn/report.py
  ### ----------------------------------- Cloud specific configuration ----------------------------------- ###
  ### ----------------------------------- ocp_cert_1 configuration --------------------------------------- ###
  # PREFIX: ocp_cert_1
  # JENKINS_URL: ''
  # JENKINS_USER: ''
  # JENKINS_PASS: ''
  # CREDS_IN_DEPLOYER: ''
  # RESTRICTED_USER_APP: ''
  # CLOUD_HOST_OVERALL: ${OCP_CERT_1_HOST}
  # CLOUD_TOKEN_OVERALL: ${OCP_CERT_1_TOKEN}
  # PROJECT: rabbitmq
  # KUBECONFIG: $OCP_CERT_1_KUBECONFIG
  ### ----------------------------------- platcert01 configuration ----------------------------------- ###
  # PREFIX: platcert01
  # JENKINS_URL: ''
  # JENKINS_USER: ''
  # JENKINS_PASS: ''
  # CREDS_IN_DEPLOYER: ''
  # RESTRICTED_USER_APP: ''
  # CLOUD_HOST_OVERALL: ${PLATCERT01_HOST}
  # CLOUD_TOKEN_OVERALL: ${PLATCERT01_TOKEN_ADMIN}
  # PROJECT: rabbitmq
  ### ----------------------------------- qa_kubernetes configuration ----------------------------------- ###
  PREFIX: qa_kubernetes_orchestration
  JENKINS_URL: ''
  JENKINS_USER: ''
  JENKINS_PASS: ''
  CREDS_IN_DEPLOYER: ''
  RESTRICTED_USER_APP: ''
  CLOUD_HOST_OVERALL: ${QA_KUBER_HOST}
  CLOUD_TOKEN_OVERALL: ${QA_KUBER_TOKEN}
  PROJECT: rabbitmq
  KUBECONFIG: $QA_KUBER_KUBECONFIG
  ### ------------------------------------------- Manifests --------------------------------------------- ###  
  LATEST_SPRINT: ''
  PREVIOUS_SPRINT: ''
  N1_RELEASE: ''
  N2_RELEASE: ''
  PREVIOUS_3PARTY: ''
  # LATEST_SPRINT: ''
  # PREVIOUS_SPRINT: ''
  # N1_RELEASE: ''
  # N2_RELEASE: ''
  # PREVIOUS_3PARTY: ''
  DEPLOY_SCHEME: full  # basic or full
  LATEST_SPRINT_TAG: ''
  PREVIOUS_SPRINT_TAG: ''

stages:
  - clean_latest_sprint_infra-passport
  - clean_previous_sprint
  - upgrade_from_previous_sprint_to_latest_sprint
  - clean_latest_sprint
  - upgrade_latest_sprint_diff_params
  - clean_n1_release
  - upgrade_from_n1_release_to_latest_sprint
  - clean_n2_release
  - upgrade_from_n2_release_to_latest_sprint
  - clean_previous_3party
  - migration_from_previous_3party_to_latest_sprint
  - clean_previous_sprint_restricted
  - upgrade_from_previous_sprint_to_latest_sprint_restricted
  - clean_latest_sprint_restricted
  - clean_latest_sprint_w/o_components
  - upgrade_latest_sprint_all_components_s3_drd
  - clean_latest_sprint_s3
  - upgrade_latest_sprint_custom_creds
  - clean_latest_sprint_s3_drd_tls-secrets
  - upgrade_latest_sprint_s3_drd_tls-certs
  - clean_latest_sprint_s3_drd
  - upgrade_latest_sprint_from_non-tls_to_tls_s3_drd
  - clean_latest_sprint_s3_drd_tls
  - clean_latest_sprint_full-at_custom-labels_nodeport
  - create_report

default:
  before_script:
    - pip config set global.index-url qubership.org/api/pypi/pypi_python_org.pypi.proxy/simple
    - pip config set global.trusted-host dockerhub.qubership.org
    - python3 -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - apk add openssh-client --update-cache --repository ${REPOSITORY_URL} --allow-untrusted
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod +x $KUBECTL
    - echo "$KUBECONFIG" > kubeconfig.env
    - export KUBECONFIG=/builds/PROD.Platform.HA/Infra.Automation/kubeconfig.env

.test-case: &test-case
  image: ${PYTHON_IMAGE}
  extends: .check_state_logs_script.run
  variables:
    ARRAY_NS: ${PROJECT}
    ALLOWED_RESTARTS_AMOUNT: 1
    ALLOWED_ERROR_LOGS_AMOUNT: 300
  tags:
    - ''
  allow_failure: true
  when: on_success

.clean_ns: &clean_ns
  - python3 "${CLEAN_NS_SCRIPT}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --cloud-namespace="${PROJECT}" --pv-list="rmq-hp-1,rmq-hp-2,rmq-hp-3,rabbitmq-backup" --cr-list="rabbitmqservices"

include:
  - project: 'PROD.Platform.HA/Infra.Automation'
    ref: pipe_image
    file: 'api2.yaml'

1-Clean [LATEST_SPRINT] Infra Passport:
  <<: *test-case
  stage: clean_latest_sprint_infra-passport
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_infra-passport.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]

2-Clean [PREVIOUS_SPRINT]:
  <<: *test-case
  stage: clean_previous_sprint
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${PREVIOUS_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"

3-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT]:
  <<: *test-case
  stage: upgrade_from_previous_sprint_to_latest_sprint
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

4-Clean [LATEST_SPRINT]:
  <<: *test-case
  stage: clean_latest_sprint
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]

5-Upgrade [LATEST_SPRINT] Diff Params:
  <<: *test-case
  stage: upgrade_latest_sprint_diff_params
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_updated.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

# Releases
6-Clean [N1_RELEASE]:
  <<: *test-case
  stage: clean_n1_release
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${N1_RELEASE}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

7-Upgrade From [N1_RELEASE] To [LATEST_SPRINT]:
  <<: *test-case
  stage: upgrade_from_n1_release_to_latest_sprint
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

8-Clean [N2_RELEASE]:
  <<: *test-case
  stage: clean_n2_release
  script:
    - *clean_ns
    - python3 "${PATCH_NS}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --namespace="${PROJECT}" --label="add"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${N2_RELEASE}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - python3 "${PATCH_NS}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --namespace="${PROJECT}" --label="remove"
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

9-Upgrade From [N2_RELEASE] To [LATEST_SPRINT]:
  <<: *test-case
  stage: upgrade_from_n2_release_to_latest_sprint
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

# 3-party upgrades
10-Clean [PREVIOUS_3PARTY]:
  <<: *test-case
  stage: clean_previous_3party
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${PREVIOUS_3PARTY}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"

11-Migration From [PREVIOUS_3PARTY] To [LATEST_SPRINT]:
  <<: *test-case
  stage: migration_from_previous_3party_to_latest_sprint
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

# Restricted
12-Clean [PREVIOUS_SPRINT] Restricted:
  <<: *test-case
  stage: clean_previous_sprint_restricted
  script:
    - *clean_ns
    - python3 "${APPLY_RESOURCES_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --namespace="${PROJECT}" --crd-tag="${PREVIOUS_SPRINT_TAG}" --service="rabbit"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_restricted.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${PREVIOUS_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
  only: { variables: [ $RESTRICTED_USER_APP != "" ] }

13-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT] Restricted:
  <<: *test-case
  stage: upgrade_from_previous_sprint_to_latest_sprint_restricted
  script:
    - python3 "${UPGRADE_CRD_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --crd-tag="${LATEST_SPRINT_TAG}" --service="rabbit"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_restricted.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $RESTRICTED_USER_APP != "" ] }

14-Clean [LATEST_SPRINT] Restricted:
  <<: *test-case
  stage: clean_latest_sprint_restricted
  script:
    - *clean_ns
    - python3 "${APPLY_RESOURCES_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --namespace="${PROJECT}" --crd-tag="${LATEST_SPRINT_TAG}" --service="rabbit"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_restricted.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
  only: { variables: [ $RESTRICTED_USER_APP != "" ] }

# Custom
15-Clean [LATEST_SPRINT] W/O Components:
  <<: *test-case
  stage: clean_latest_sprint_w/o_components
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_without_components.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

16-Upgrade [LATEST_SPRINT] All Components S3 DRD:
  <<: *test-case
  stage: upgrade_latest_sprint_all_components_s3_drd
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3_drd.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

17-Clean [LATEST_SPRINT] S3:
  <<: *test-case
  stage: clean_latest_sprint_s3
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

18-Upgrade [LATEST_SPRINT] Custom Creds:
  <<: *test-case
  stage: upgrade_latest_sprint_custom_creds
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_updated_creds.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

19-Clean [LATEST_SPRINT] S3 DRD TLS Secrets:
  <<: *test-case
  stage: clean_latest_sprint_s3_drd_tls-secrets
  script:
    - *clean_ns 
    - $KUBECTL create -f ./resources/rabbitmq_tls_secret.yml -n ${PROJECT} || true
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3_drd_tls_secrets.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

20-Upgrade [LATEST_SPRINT] S3 DRD TLS Certs:
  <<: *test-case
  stage: upgrade_latest_sprint_s3_drd_tls-certs
  script:
    - $KUBECTL delete secrets rabbitmq-tls-secret rabbitmq-drd-tls-secret rabbitmq-backup-daemon-tls-secret -n ${PROJECT} || true
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3_drd_tls_certs.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update" --request-type="post"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

21-Clean [LATEST_SPRINT] S3 DRD:
  <<: *test-case
  stage: clean_latest_sprint_s3_drd
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3_drd.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

22-Upgrade [LATEST_SPRINT] From Non-TLS To TLS S3 DRD:
  <<: *test-case
  stage: upgrade_latest_sprint_from_non-tls_to_tls_s3_drd
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3_drd_tls.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

23-Clean [LATEST_SPRINT] TLS S3 DRD:
  <<: *test-case
  stage: clean_latest_sprint_s3_drd_tls
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_s3_drd_tls.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
  only: { variables: [ $DEPLOY_SCHEME == "full" ] }

24-Clean [LATEST_SPRINT] Full-AT Custom-Labels Nodeport:
  <<: *test-case
  stage: clean_latest_sprint_full-at_custom-labels_nodeport
  script:
    - *clean_ns
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/rabbitmq/${PREFIX}/rabbit_clean_sc_full_tests.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
    
Report:
  image: ${PYTHON_IMAGE}
  tags:
    - ''
  when: manual
  stage: create_report
  script:
    - python3 ${REPORT_SCRIPT} --pipeline_id="${CI_PIPELINE_ID}" --token="${GIT_TOKEN}" --webex-room-id="${WEBEX_CI_ROOM_ID}" --webex-token="${WEBEX_CI_TOKEN}" --versions="LATEST_SPRINT=${LATEST_SPRINT},PREVIOUS_SPRINT=${PREVIOUS_SPRINT},N1_RELEASE=${N1_RELEASE},N2_RELEASE=${N2_RELEASE}"
  artifacts:
    paths:
      - "*.html"
