variables:
  PYTHON_IMAGE: pipe_image_latest
  JOB_NAME_CLEAN: ''
  JOB_NAME_UPDATE: ''
  DEPLOY_SCRIPT_APP: /scripts/external_platform_library_builtIn/deploy\_with\_deployer.py
  UPGRADE_CRD_SCRIPT: /scripts/external_platform_library_builtIn/upgrade_crd.py
  APPLY_RESOURCES_SCRIPT: /scripts/external_platform_library_builtIn/prepare_restricted_resources.py
  CLEAN_NS_SCRIPT: /scripts/external_platform_library_builtIn/clean_namespace.py
  PATCH_NS: /scripts/external_platform_library_builtIn/patch_ns_restricted.py
  REPORT_SCRIPT: /scripts/external_platform_library_builtIn/report.py
  ### ------------------------------- Cloud specific configuration --------------------------------- ###
  ### --------------------------------- ocp_cert_1 configuration ----------------------------------- ###
  PREFIX: ocp_cert_1
  JENKINS_URL: ''
  JENKINS_USER: ''
  JENKINS_PASS: ''
  CREDS_IN_DEPLOYER: ''
  RESTRICTED_USER_APP: ''
  CLOUD_HOST_OVERALL: ${OCP_CERT_1_HOST}
  CLOUD_TOKEN_OVERALL: ${OCP_CERT_1_TOKEN}
  PROJECT: redis
  ### ----------------------------------- platcert01 configuration ----------------------------------- ###
#  PREFIX: platcert01
#  JENKINS_URL: ''
#  JENKINS_USER: ''
#  JENKINS_PASS: ''
#  CREDS_IN_DEPLOYER: ''
#  RESTRICTED_USER_APP: ''
#  CLOUD_HOST_OVERALL: ${PLATCERT01_HOST}
#  CLOUD_TOKEN_OVERALL: ${PLATCERT01_TOKEN_ADMIN}
#  PROJECT: redis
  ### -------------------------------- qa_kubernetes configuration --------------------------------- ###
  # PREFIX: qa_kubernetes_orchestration
  # JENKINS_URL: ''
  # JENKINS_USER: ''
  # JENKINS_PASS: ''
  # CREDS_IN_DEPLOYER: ''
  # RESTRICTED_USER_APP: ''
  # CLOUD_HOST_OVERALL: ${QA_KUBER_HOST}
  # CLOUD_TOKEN_OVERALL: ${QA_KUBER_TOKEN}
  # PROJECT: redis
  ### ----------------------------------------- Manifests ------------------------------------------ ###
  LATEST_SPRINT: ''
  PREVIOUS_SPRINT: ''
  N1_RELEASE: ''
  N2_RELEASE: ''
  # Vault
  VAULT_URL: http://vault-operator.apps.qa-kubernetes.openshift.sdntest.qubership.org/
  VAULT_TOKEN: "root"
  # Variables for restricted deploy
  LATEST_SPRINT_TAG: ''
  PREVIOUS_SPRINT_TAG: ''


stages:
  - clean_previous_sprint
  - upgrade_from_previous_to_latest
  - clean_latest_sprint
  - upgrade_to_latest_diff_params
  - clean_previous_sprint_restricted
  - update_from_previous_to_latest_restricted
  - clean_latest_sprint_restricted
  - clean_n1_release
  - upgrade_from_n1_to_latest
  - clean_n2_release
  - upgrade_from_n2_to_latest
  - clean_latest_sprint_tls
  - clean_latest_sprint_vault
  - clean_latest_sprint_vault_tls
  - clean_latest_sprint_without_dbaas
  - clean_latest_sprint_non_default_creds
  - create_report



default:
  before_script:
    - apk add curl
    - pip config set global.index-url qubership.org/api/pypi/pypi_python_org.pypi.proxy/simple
    - pip config set global.trusted-host dockerhub.qubership.org
    - python3 -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - echo CLOUD_HOST $CLOUD_HOST_OVERALL


.test-case: &test-case
  image: ${PYTHON_IMAGE}
  extends: .check_state_logs_script.run
  variables:
    CLOUD_HOST: ${CLOUD_HOST_OVERALL}
    CLOUD_TOKEN: ${CLOUD_TOKEN_OVERALL}
    ARRAY_NS: ${PROJECT}
    ALLOWED_RESTARTS_AMOUNT: 1
    ALLOWED_ERROR_LOGS_AMOUNT: 100
  tags:
    - ''
  allow_failure: true
  #when: manual
  when: on_success

.clean_ns: &clean_ns
  - python3 "${CLEAN_NS_SCRIPT}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --cloud-namespace="${PROJECT}" --cr-list="dbaasredisadapters"

include:
  - project: 'PROD.Platform.HA/Infra.Automation'
    ref: pipe_image
    file: 'api2.yaml'


1-Clean [PREVIOUS_SPRINT]:
  <<: *test-case
  stage: clean_previous_sprint
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${PREVIOUS_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - chmod +x ./custom_scripts/create_db_instance.sh
    - ./custom_scripts/create_db_instance.sh

2-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT]:
  <<: *test-case
  stage: upgrade_from_previous_to_latest
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

3-Clean [LATEST_SPRINT]:
  <<: *test-case
  stage: clean_latest_sprint
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]

4-Upgrade [LATEST_SPRINT] Diff Params:
  <<: *test-case
  stage: upgrade_to_latest_diff_params
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/update_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

# Releases
5-Clean [N1_RELEASE]:
  <<: *test-case
  stage: clean_n1_release
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${N1_RELEASE}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"

6-Upgrade From [N1_RELEASE] To [LATEST_SPRINT]:
  <<: *test-case
  stage: upgrade_from_n1_to_latest
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

7-Clean [N2_RELEASE]:
  <<: *test-case
  stage: clean_n2_release
  script:
    - python3 "${PATCH_NS}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --namespace="${PROJECT}" --label="add"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${N2_RELEASE}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - python3 "${PATCH_NS}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --namespace="${PROJECT}" --label="remove"

8-Upgrade From [N2_RELEASE] To [LATEST_SPRINT]:
  <<: *test-case
  stage: upgrade_from_n2_to_latest
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]

# Custom
9-Clean [LATEST_SPRINT] TLS:
  <<: *test-case
  stage: clean_latest_sprint_tls
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_with_tls.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]

10-Clean [LATEST_SPRINT] Vault:
  <<: *test-case
  stage: clean_latest_sprint_vault
  script:
    - |
      token="${VAULT_TOKEN}"
      vurl="${VAULT_URL}"
      sed -i 's,token:*,token:\ '$token',' ./templates/${PREFIX}/clean_with_vault.yml
      sed -i 's,url:*,url:\ '$vurl',' ./templates/${PREFIX}/clean_with_vault.yml
      python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_with_vault.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
  only: { variables: [ $VAULT_TOKEN != "" ] }

11-Clean [LATEST_SPRINT] Vault TLS:
  <<: *test-case
  stage: clean_latest_sprint_vault_tls
  script:
    - |
      token="${VAULT_TOKEN}"
      vurl="${VAULT_URL}"
      sed -i 's,token:*,token:\ '$token',' ./templates/${PREFIX}/clean_with_vault_tls.yml
      sed -i 's,url:*,url:\ '$vurl',' ./templates/${PREFIX}/clean_with_vault_tls.yml
      python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_with_vault_tls.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
  only: { variables: [ $VAULT_TOKEN != "" ] }

12-Clean [LATEST_SPRINT] Without Dbaas Or Backup:
  <<: *test-case
  stage: clean_latest_sprint_without_dbaas
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_without_dbaas.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]

13-Clean [LATEST_SPRINT] Non Default Creds:
  <<: *test-case
  stage: clean_latest_sprint_non_default_creds
  script:
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_non_default_creds.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]

# Restricted
14-Clean [PREVIOUS_SPRINT] Restricted:
  <<: *test-case
  stage: clean_previous_sprint_restricted
  script:
    - *clean_ns
    - python3 "${APPLY_RESOURCES_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --namespace="${PROJECT}" --crd-tag="${PREVIOUS_SPRINT_TAG}"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_restricted.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${PREVIOUS_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
  only: { variables: [ $RESTRICTED_USER_APP != "" ] }

15-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT] Restricted:
  <<: *test-case
  stage: update_from_previous_to_latest_restricted
  script:
    - python3 "${UPGRADE_CRD_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --crd-tag="${LATEST_SPRINT_TAG}"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_restricted.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
    - !reference [.template_job_status, script]
  only: { variables: [ $RESTRICTED_USER_APP != "" ] }

16-Clean [LATEST_SPRINT] Restricted:
  <<: *test-case
  stage: clean_latest_sprint_restricted
  script:
    - *clean_ns
    - python3 "${APPLY_RESOURCES_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --namespace="${PROJECT}" --crd-tag="${LATEST_SPRINT_TAG}"
    - python3 "${DEPLOY_SCRIPT_APP}" -f "./templates/${PREFIX}/clean_deploy_restricted.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
    - !reference [.template_job_status, script]
  only: { variables: [ $RESTRICTED_USER_APP != "" ] }

Report:
  image: ${PYTHON_IMAGE}
  tags:
    - ''
  when: on_success
  stage: create_report
  script:
    - python3 ${REPORT_SCRIPT} --pipeline_id="${CI_PIPELINE_ID}" --token="${GIT_TOKEN}" --webex-room-id="${WEBEX_CI_ROOM_ID}" --webex-token="${WEBEX_CI_TOKEN}" --versions="LATEST_SPRINT=${LATEST_SPRINT}, PREVIOUS_SPRINT=${PREVIOUS_SPRINT},N1_RELEASE=${N1_RELEASE},N2_RELEASE=${N2_RELEASE},LATEST_SPRINT_TAG=${LATEST_SPRINT_TAG},PREVIOUS_SPRINT_TAG=${PREVIOUS_SPRINT_TAG}"
  artifacts:
    paths:
      - "*.html"
