NAMESPACE: jaeger-helm
jaeger:
  serviceName: jaeger-test
  prometheusMonitoring: true
  prometheusMonitoringDashboard: true
  storage:
    type: cassandra
cassandraSchemaJob:
  install: true
  host: cassandra.cassandra-helm.svc
  keyspace: jaeger
  password: ''
  username: admin
  datacenter: dc1
  mode: prod
  securityContext:
    runAsUser: 2000
    fsGroup: 2000
agent:
  install: true
  securityContext:
    runAsUser: 2000
    fsGroup: 2000
collector:
  install: true
  securityContext:
    runAsUser: 2000
    fsGroup: 2000
hotrod:
  install: true
  securityContext:
    runAsUser: 2000
    fsGroup: 2000
  agent:
    host: jaeger-agent.jaeger-helm.svc
  ingress:
    install: true
    host: jaeger-hotrod.{{env_pipe_domain_name}}
query:
  install: true
  ingress:
    install: true
    host: jaeger-query.{{env_pipe_domain_name}}
  securityContext:
    runAsUser: 2000
    fsGroup: 2000
integrationTests:
  install: true
  tags: smoke
  jaegerServiceName: jaeger-test
  linkForGenerator: http://jaeger-collector:9411
