---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: database-checker
  template:
    metadata:
      labels:
        name: database-checker
      name: database-checker
    spec:
      containers:
        - image: qubership.org:/paas_demo-database-checker:main_latest
          imagePullPolicy: Always
          name: database-checker
          ports:
            - name: http
              containerPort: 8092
              protocol: TCP
          env:
            - name: TPS
              value: '0.001'
            - name: MONGO
              value: >-
                mongodb://root:root@mongos.mongo-helm:27017/test?authSource=admin
            - name: PG
              value: >-
                user='postgres' host='pg-patroni.postgres-helm' password=''
            - name: ES_URL
              value: http://admin:admin@opensearch.opensearch-cloud:9200
            - name: CASS_URL
              value: cassandra.cassandra-helm.svc
            - name: CASS_USER
              value: admin
            - name: CASS_PASS
              value: admin
            - name: CASS_DC
              value: "'dc1': '3'"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.kafka-helm:9092
            - name: KAFKA_USER
              value: admin
            - name: KAFKA_PASS
              value: admin
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_PLAINTEXT
            - name: CLUSTER
              value: platcert01cluster
            - name: CLICKHOUSE_URL
              value: clickhouse-cluster.clickhouse-helm.svc
            - name: CLICKHOUSE_USER
              value: clickhouse
            - name: CLICKHOUSE_PASS
              value: clickhouse
            - name: ARANGO_URL
              value: arangodb-leader.arango-helm
            - name: ARANGO_USER
              value: root
            - name: ARANGO_PASS
              value: ''
          resources:
            limits:
              cpu: 600m
              memory: 640M
            requests:
              cpu: 500m
              memory: 512M
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: database-checker
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8092
  selector:
    name: database-checker
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: database-checker
  namespace: db-checker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: database-checker.db-checker.{{env_pipe_domain_name}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: database-checker
                port:
                  number: 80
