cassandra:
  install: true
  deploymentSchema:
    dataCenters:
      - name: dc1
        replicas: 3
        seeds: 1
        storage:
          size: 1Gi
          storageClasses:
            - {{env_pipe_storage_class}}
backupDaemon:
  install: true
  storage:
    storageClasses:
      - {{env_pipe_storage_class}}
robotTests:
  install: true