opensearch:
  securityConfig:
    authc:
      basic:
        username: admin
        password: ''
  securityContextCustom:
    runAsUser: 1000
    fsGroup: 1000
  main
    replicas: 3
    resources:
      limits:
        cpu: 2500m
        memory: 2048Mi
      requests:
        cpu: 200m
        memory: 1024Mi
    javaOpts: -Xms512m -Xmx512m
    persistence:
      storageClass: {{env_pipe_storage_class}}
      size: 5Gi
  snapshots:
    enabled: false
    persistentVolumeType: ""
    persistentVolume: ""
    repositoryName: snapshots
    volumeSize: 3G
    s3:
      enabled: false
      pathStyleAccess: true
      url: {{env_pipe_s3_minio}}/
      bucket: opensearch-qa-k8s
      keyId: ''
      keySecret: ''
      basePath: ""
      region: ""
  client:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - opensearch-cloud-service.{{env_pipe_domain_name}}
dbaasAdapter:
  enabled: false
monitoring:
  includeIndices: true
  slowQueries:
    enabled: true
    topNumber: 10
    processingIntervalMinutes: 5
    minSeconds: 1
    indicesPattern: "*"
  thresholds:
    lagAlert: null
    slowQuerySecondsAlert: 10
dashboards:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: dashboards-opensearch-cloud-service.{{env_pipe_domain_name}}
        paths:
          - path: /
curator:
  enabled: false
integrationTests:
  enabled: true
  tags: smoke
statusProvisioner:
  podReadinessTimeout: 1200
  integrationTestsTimeout: 1200
