webserverSecretKey:''
fernetKey:''
ingress:
  enabled: true
  web:
    hosts:
      - web3.airflow-helm.{{env_pipe_domain_name}}
customPreinstallJob:
  extraSecrets:
    dbaas-connection-params-preins:
      stringData: |
        DBAAS_HOST: '{{env_pipe_dbaas_aggregator_registration_address}}'
        DBAAS_USER: 'cluster-dba'
        DBAAS_PASSWORD: ''
        DBAAS_PG_DB_OWNER: 'airflow'
        DBAAS_PG_BACKUP_DISABLED: 'true'
        DBAAS_PG_MICROSERVICE_NAME: 'airflow'
        DBAAS_REDIS_DB_OWNER: 'airflow'
        DBAAS_REDIS_BACKUP_DISABLED: 'true'
        DBAAS_REDIS_MICROSERVICE_NAME: 'airflowdbaas'
        AIRFLOW_EXECUTOR: 'airflowdbaas'
  extraEnvFrom: |
    - secretRef:
        name: 'dbaas-connection-params-preins'
extraSecrets:
  dbaas-connection-params-main:
    stringData: |
      DBAAS_HOST: '{{env_pipe_dbaas_aggregator_registration_address}}'
      DBAAS_USER: 'cluster-dba'
      DBAAS_PASSWORD: ''
      DBAAS_PG_DB_OWNER: 'airflow'
      DBAAS_PG_BACKUP_DISABLED: 'true'
      DBAAS_PG_MICROSERVICE_NAME: 'airflow'
      DBAAS_REDIS_DB_OWNER: 'airflow'
      DBAAS_REDIS_BACKUP_DISABLED: 'true'
      DBAAS_REDIS_MICROSERVICE_NAME: 'airflowdbaas'
      AIRFLOW_EXECUTOR: 'airflowdbaas'
  git-credentials:
    stringData: |
      GIT_SYNC_USERNAME: 'CloudPlatformCIUser'
      GIT_SYNC_PASSWORD: ''
      GITSYNC_USERNAME: 'CloudPlatformCIUser'
      GITSYNC_PASSWORD: ''
dags:
  gitSync:
    wait: 5
    subPath: tests_dags_image/dags
    repo: https://git.qubership.org/Services/airflow.git
    branch: main
    credentialsSecret: git-credentials
    uid: null
    enabled: true
    maxFailures: 0
    securityContexts:
      container:
        capabilities:
          drop:
            - ALL
        allowPrivilegeEscalation: false
webserver:
  enabled: true
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: ''
DEPLOYMENT_RESOURCE_NAME: airflow
SERVICE_NAME: airflow
ARTIFACT_DESCRIPTOR_VERSION: airflow
API_DBAAS_ADDRESS: {{env_pipe_dbaas_aggregator_registration_address}}
DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME: cluster-dba
DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD: ''
platformAirflowMonitoring: true
serviceMonitor:
  enabled: true
prometheusRule:
  enabled: true
statsd:
  enabled: true
serviceMonitorStatsd:
  enabled: true
config:
  api:
    auth_backend: airflow.api.auth.backend.basic_auth
  secrets:
    backend: ncdbaasintegration.dbaas_secrets_backend.DBAASSecretsBackend
    backend_kwargs: "{{ .Values.nc_secrets_backend_params | toJson }}"
integrationTests:
  enabled: true
  tags: smoke
  airflowHost: "airflow-operator-webserver"
  airflowPort: 8080
  workerServiceName: "airflow-operator-worker"
  webServiceName: "airflow-operator-webserver"
  schedulerDeployment: "airflow-operator-scheduler"