publicCloudName: "{{env_pipe_public_cloud_name}}"
prometheus:
  install: false
alertManager:
  install: true
grafana:
  ingress:
    host: grafana.{{env_pipe_domain_name}}
victoriametrics:
  vmOperator:
    install: true
  vmAgent:
    install: true
  vmSingle:
    install: true
    storage:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: {{env_pipe_storage_class}}
  vmAlertManager:
    install: true
    ingress:
      host: vmalertmanager.{{env_pipe_domain_name}}
  vmAlert:
    install: true
    ingress:
      host: vmalert.{{env_pipe_domain_name}}
  vmAuth:
    install: true
    ingress:
      host: vmauth.{{env_pipe_domain_name}}
      install: true
integrationTests:
  install: true

