name: mistral-service
mistralCommonParams:
  postgres:
    dbName: mistral_regr
    host: pg-patroni.postgres-helm.svc
    port: "5432"
  rabbit:
    host: rabbitmq.rabbit-helm.svc
    port: "5672"
    vhost: mistral_regr
  kafkaNotifications:
    enabled: false
  auth:
    enable: "False"
  securityProfile: dev
secrets:
  pgAdminPassword: ''
  pgAdminUser: postgres
  rabbitAdminPassword: ''
  rabbitAdminUser: admin
integrationTests:
  enabled: true
  runTestsOnly: false
  waitTestResultOnJob: true
  mistralReadyTimeout: 180
  runAsUser: 5000
CLOUD_CORE_INTEGRATION_ENABLED: False