apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-service-operator-akhq
rules:
  - apiGroups:
      - qubership.org
    resources:
      - akhqconfigs
      - akhqconfigs/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
