apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: arango-operator-operator-crb-pv
subjects:
  - kind: ServiceAccount
    name: arangodb-operator-sa
    namespace: arangodb
roleRef:
  kind: ClusterRole
  name: arango-operator-operator-cr-pv
  apiGroup: rbac.authorization.k8s.io
