name: 'Verify Monitoring Installation Action'
description: 'A GitHub Action to verify tests, get logs from pods'
inputs:
  namespace:
    description: 'See verify_installation.namespace'
    required: true
    default: monitoring
  test_completion_max_retries:
    description: 'See verify_installation.test_completion_max_retries'
    required: true
    default: 60
  test_completion_retry_interval:
    description: 'See verify_installation.test_completion_retry_interval'
    required: true
    default: '10s'
  service_ready_max_retries:
    description: 'See verify_installation.test_completion_max_retries'
    required: true
    default: 150
  service_ready_retry_interval:
    description: 'See verify_installation.test_completion_retry_interval'
    required: true
    default: '10s'
  service_branch:
    description: 'See verify_installation.service_branch'
    required: true
    default: ''
  cr_kind:
    description: 'See verify_installation.cr_kind'
    required: true
    default: 'PlatformMonitoring'
  cr_name:
    description: 'See verify_installation.cr_name'
    required: true
    default: 'platformmonitoring'


runs:
  using: 'composite'
  steps:
    - name: Run verify_installation action for Monitoring
      uses: ./qubership-test-pipelines/actions/shared/verify_installation
      with:
        namespace: ${{inputs.namespace}}
        test_completion_max_retries: ${{inputs.test_completion_max_retries}}
        test_completion_retry_interval: ${{inputs.test_completion_retry_interval}}
        service_ready_max_retries: ${{inputs.service_ready_max_retries}}
        service_ready_retry_interval: ${{inputs.service_ready_retry_interval}}
        service_branch: ${{inputs.service_branch}}
        cr_kind: ${{inputs.cr_kind}}
        cr_name: ${{inputs.cr_name}}
