PREFIX: fenrir_orchestration
JENKINS_URL: ''
JENKINS_USER: ''
JENKINS_PASS: ''
CREDS_IN_DEPLOYER: ''
RESTRICTED_USER_APP: ''
CLOUD_HOST_OVERALL: ${FENRIR_KUBER_HOST}
CLOUD_TOKEN_OVERALL: ${FENRIR_KUBER_TOKEN}
PYTHON_IMAGE: pipe_image_new_latest