#PREFIX: qa_kubernetes
#JENKINS_URL: ''
#JOB_NAME_CLEAN: ''
#JOB_NAME_UPDATE: ''
#JENKINS_USER: ''
#JENKINS_PASS: ''
#CREDS_IN_DEPLOYER: ''
#RESTRICTED_USER_APP: ''
#CLOUD_HOST_OVERALL: ${QA_KUBER_HOST}
#CLOUD_TOKEN_OVERALL: ${QA_KUBER_TOKEN}
#PYTHON_IMAGE: pipe_image_new_latest
#KUBECONFIG: $QA_KUBER_KUBECONFIG


PREFIX: qa_kubernetes_orchestration
JENKINS_URL: ''
JOB_NAME_CLEAN: ''
JOB_NAME_UPDATE: ''
JENKINS_USER: ''
JENKINS_PASS: ''
CREDS_IN_DEPLOYER: ''
RESTRICTED_USER_APP: ''
CLOUD_HOST_OVERALL: ${QA_KUBER_HOST}
CLOUD_TOKEN_OVERALL: ${QA_KUBER_TOKEN}
PYTHON_IMAGE: pipe_image_new_latest
KUBECONFIG: $QA_KUBER_KUBECONFIG