apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-fluentbit-aggregator-cluster-role
  labels:
    name: logging-fluentbit-aggregator-cluster-role
    app.kubernetes.io/name: logging-fluentbit-aggregator-cluster-role
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - logging-fluentbit-aggregator
