variables:
  PYTHON_IMAGE: pipe_image_latest
  JOB_NAME_CLEAN: ''
  JOB_NAME_UPDATE: ''
  DEPLOY_SCRIPT: /scripts/external_platform_library_builtIn/deploy\_with\_deployer.py
  UPGRADE_CRD_SCRIPT: /scripts/external_platform_library_builtIn/upgrade_crd.py
  APPLY_RESOURCES_SCRIPT: /scripts/external_platform_library_builtIn/prepare_restricted_resources.py
  CLEAN_NS_SCRIPT: /scripts/external_platform_library_builtIn/clean_namespace.py
  PATCH_NS_SCRIPT: /scripts/external_platform_library_builtIn/patch_ns_restricted.py
  REPORT_SCRIPT: /scripts/external_platform_library_builtIn/report.py
  ### ----------------------------------- Cloud specific configuration ----------------------------------- ###
  ### ----------------------------------- ocp_cert_1 configuration --------------------------------------- ###
#  PREFIX: ocp_cert_1
#  JENKINS_URL: ''
#  JENKINS_USER: ''
#  JENKINS_PASS: ''
#  CREDS_IN_DEPLOYER: ''
#  RESTRICTED_USER_APP: ''
#  CLOUD_HOST_OVERALL: ${OCP_CERT_1_HOST}
#  CLOUD_TOKEN_OVERALL: ${OCP_CERT_1_TOKEN}
#  PROJECT: arangodb
  ### ----------------------------------- platcert01 configuration ----------------------------------- ###
#  PREFIX: platcert01
#  JENKINS_URL: ''
#  JENKINS_USER: ''
#  JENKINS_PASS: ''
#  CREDS_IN_DEPLOYER: ''
#  RESTRICTED_USER_APP: ''
#  CLOUD_HOST_OVERALL: ${PLATCERT01_HOST}
#  CLOUD_TOKEN_OVERALL: ${PLATCERT01_TOKEN_ADMIN}
#  PROJECT: arangodb
  ### ----------------------------------- qa_kubernetes configuration ----------------------------------- ###
  PREFIX: qa_kubernetes_orchestration
  JENKINS_URL: ''
  JENKINS_USER: ''
  JENKINS_PASS: ''
  CREDS_IN_DEPLOYER: ''
  RESTRICTED_USER_APP: ''
  CLOUD_HOST_OVERALL: ${QA_KUBER_HOST}
  CLOUD_TOKEN_OVERALL: ${QA_KUBER_TOKEN}
  PROJECT: arangodb
  ### ----------------------------------------- Manifests ------------------------------------------ ###
  N2_RELEASE: ''
  N1_RELEASE: ''
  PREVIOUS_SPRINT: ''
  LATEST_SPRINT: ''
  LATEST_SPRINT_TAG: ''
  PREVIOUS_SPRINT_TAG: ''

stages:
   - clean_previous_sprint
   - update_to_latest
   - clean_latest
   - update_diff_params
   - update_to_tls
   - clean_latest_tls
   - clean_n1_release
   - upgrade_from_n1_to_latest_sprint
   - clean_n2_release
   - upgrade_from_n2_to_latest_sprint
   - clean_previous_sprint_restricted
   - upgrade_to_latest_sprint_restricted
   - clean_latest_sprint_restricted
   - create_report

default:
  before_script:
    - pip config set global.index-url qubership.org/api/pypi/pypi_python_org.pypi.proxy/simple
    - pip config set global.trusted-host dockerhub.qubership.org
    - python3 -m pip install --upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - echo CLOUD_HOST $CLOUD_HOST

.test-case: &test-case
  image: ${PYTHON_IMAGE}
  extends: .check_state_logs_script.run
  variables:
    CLOUD_HOST: ${CLOUD_HOST_OVERALL}
    CLOUD_TOKEN: ${CLOUD_TOKEN_OVERALL}
    ARRAY_NS: ${PROJECT}
    ALLOWED_RESTARTS_AMOUNT: 3
    ALLOWED_ERROR_LOGS_AMOUNT: 700
  tags:
    - ''
  allow_failure: true
  # when: manual
  when: on_success

.clean_ns: &clean_ns
  - python3 "${CLEAN_NS_SCRIPT}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --cloud-namespace="${PROJECT}" --pv-list="arangodb-pv-agency-left-1,arangodb-pv-agency-left-2,arangodb-pv-agency-left-3,arangodb-pv-db-app-left-1,arangodb-pv-db-app-left-2,arangodb-pv-db-data-left-1,arangodb-pv-db-data-left-2"

include:
  - project: 'PROD.Platform.HA/Infra.Automation'
    ref: pipe_image
    file: 'api2.yaml'

1-Clean [PREVIOUS_SPRINT]:
    <<: *test-case
    stage: clean_previous_sprint
    script:
      - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_APP_k8s.yml"  --artifact="${PREVIOUS_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"

2-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT]:
    <<: *test-case
    stage: update_to_latest
    script:
      - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_APP_k8s.yml" --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
      - !reference [.template_job_status, script]

3-Clean [LATEST_SPRINT]:
    <<: *test-case
    stage: clean_latest
    script:
      - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_fulltest_APP_k8s.yml"  --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
      - !reference [.template_job_status, script]

4-Upgrade [LATEST_SPRINT] Diff Params:
    <<: *test-case
    stage: update_diff_params
    script:
      - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_update_APP_k8s.yml" --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
      - !reference [.template_job_status, script]

5-Upgrade [LATEST_SPRINT] From Non-TLS To TLS:
    <<: *test-case
    stage: update_to_tls
    script:
      - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_update_tls_APP_k8s.yml" --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
      - !reference [ .template_job_status, script ]

6-Clean [LATEST_SPRINT] TLS:
    <<: *test-case
    stage: clean_latest_tls
    script:
      - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_tls_APP_k8s.yml"  --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
      - !reference [.template_job_status, script]

7-Clean [N1_RELEASE]:
   <<: *test-case
   stage: clean_n1_release
   script:
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_APP_k8s.yml"  --artifact="${N1_RELEASE}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"

8-Upgrade From [N1_RELEASE] To [LATEST_SPRINT]:
   <<: *test-case
   stage: upgrade_from_n1_to_latest_sprint
   script:
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_APP_k8s.yml" --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
     - !reference [.template_job_status, script]

9-Clean [N2_RELEASE]:
   <<: *test-case
   stage: clean_n2_release
   script:
     - python3 "${PATCH_NS_SCRIPT}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --namespace="${PROJECT}" --label="add"
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_APP_k8s.yml"  --artifact="${N2_RELEASE}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
     - python3 "${PATCH_NS_SCRIPT}" --cloud-token="${CLOUD_TOKEN}" --cloud-host="${CLOUD_HOST}" --namespace="${PROJECT}" --label="remove"

10-Upgrade From [N2_RELEASE] To [LATEST_SPRINT]:
   <<: *test-case
   stage: upgrade_from_n2_to_latest_sprint
   script:
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_APP_k8s.yml" --artifact="${LATEST_SPRINT}" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${CREDS_IN_DEPLOYER}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
     - !reference [.template_job_status, script]

 # Restricted
11-Clean [PREVIOUS_SPRINT] Restricted:
   <<: *test-case
   stage: clean_previous_sprint_restricted
   script:
     - *clean_ns
     - python3 "${APPLY_RESOURCES_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --namespace="${PROJECT}" --crd-tag="${PREVIOUS_SPRINT_TAG}"
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_restricted_APP_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${PREVIOUS_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
   only: { variables: [ $RESTRICTED_USER_APP != "" ] }

12-Upgrade From [PREVIOUS_SPRINT] To [LATEST_SPRINT] Restricted:
   <<: *test-case
   stage: upgrade_to_latest_sprint_restricted
   script:
     - python3 "${UPGRADE_CRD_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --crd-tag="${LATEST_SPRINT_TAG}"
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_restricted_APP_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_UPDATE}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Rolling Update"
     - !reference [.template_job_status, script]
   only: { variables: [ $RESTRICTED_USER_APP != "" ] }

13-Clean [LATEST_SPRINT] Restricted:
   <<: *test-case
   stage: clean_latest_sprint_restricted
   script:
     - *clean_ns
     - python3 "${APPLY_RESOURCES_SCRIPT}" --cloud-host="${CLOUD_HOST}" --cloud-token="${CLOUD_TOKEN}" --namespace="${PROJECT}" --crd-tag="${LATEST_SPRINT_TAG}"
     - python3 "${DEPLOY_SCRIPT}" -f "./templates/${PREFIX}/arango_install_restricted_APP_k8s.yml" --jenkins-user="${JENKINS_USER}" --jenkins-pass="${JENKINS_PASS}" --job-name="${JOB_NAME_CLEAN}" --jenkins-url="${JENKINS_URL}" --os-creds="${RESTRICTED_USER_APP}" --artifact="${LATEST_SPRINT}" --project="${PREFIX}-${PROJECT}" --deploy-mode="Clean Deploy"
     - !reference [.template_job_status, script]
   only: { variables: [ $RESTRICTED_USER_APP != "" ] }

Report:
  image: ${PYTHON_IMAGE}
  tags:
    - ''
  when: manual
  # when: on_success
  stage: create_report
  script:
    - python3 ${REPORT_SCRIPT} --pipeline_id="${CI_PIPELINE_ID}" --token="${GIT_TOKEN}" --webex-room-id="${WEBEX_CI_ROOM_ID}" --webex-token="${WEBEX_CI_TOKEN}" --versions="LATEST_SPRINT=${LATEST_SPRINT}, PREVIOUS_SPRINT=${PREVIOUS_SPRINT}, N1_RELEASE=${N1_RELEASE}, N2_RELEASE=${N2_RELEASE}, LATEST_SPRINT_TAG=${LATEST_SPRINT_TAG}, PREVIOUS_SPRINT_TAG=${PREVIOUS_SPRINT_TAG}"
  artifacts:
    paths:
      - "*.html"
