kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: logging-fluentbit-cluster-role
  labels:
    name: logging-fluentbit-cluster-role
    app.kubernetes.io/name: logging-fluentbit-cluster-role
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: manually
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - namespaces
      - events
      - endpoints
      - nodes
      - nodes/proxy
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - logging-fluentbit