kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-review-es-crb-opensearch
subjects:
  - kind: ServiceAccount
    name: opensearch-service-operator
    namespace: opensearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
