kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: streaming-service-operator-connector-streaming-service
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: streaming-service
    meta.helm.sh/release-namespace: streaming-service
subjects:
  - kind: ServiceAccount
    name: streaming-service-operator
    namespace: streaming-service
roleRef:
  kind: ClusterRole
  name: streaming-service-operator-connector-streaming-service
  apiGroup: rbac.authorization.k8s.io
