JOB_NAME: ''
JENKINS_URL: ''
TOKEN_NAME: CLOUD_TOKEN
CLOUD_URL: ''
CLOUD_NAMESPACE: jaeger
DESCRIPTOR_NAME: DESCRIPTOR_URL
DEPL\_MODE\: upgrade
KUBECTL_VERSION: 1.18.4
HELM_VERSION: 3.2.1
ADDITIONAL_OPTIONS: []
DEPLOYMENT_PARAMETERS: |
  jaeger:
    storage:
      type: elasticsearch
  elasticsearch:
    client:
      username: OTQyMjcyOGJmOTIy
      password: ''
      url: elasticsearch.elasticsearch-cluster.svc:9200
    indexCleaner:
      install: true
    lookback:
      install: true
    rollover:
      install: true
  agent:
    install: true
  collector:
    install: true
  hotrod:
    install: true
    agent:
      host: jaeger-app-agent.jaeger.svc
      port: 6831
    route:
      install: true
      host: "hotrod-jaeger-test.dr311qa-arbiter.openshift.sdntest.qubership.org"
  query:
    install: true
    route:
      install: true
      host: "query-jaeger-test.dr311qa-arbiter.openshift.sdntest.qubership.org"
