kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zookeeper-service-operator
subjects:
  - kind: ServiceAccount
    name: zookeeper-service-operator
    namespace: zookeeper-service
roleRef:
  kind: ClusterRole
  name: zookeeper-service-operator
  apiGroup: rbac.authorization.k8s.io
